version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pencit_db
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
  
volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
