version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: kelompok-2_backend
    environment:
      - MONGO_URI=mongodb://kelompok-2_mongo-db:27017/pencit_db
      - HOST_URL=http://kelompok-2_frontend:5011
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks:
      - app-network

  mongo:
    image: mongo:4
    container_name: kelompok-2_mongo-db
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: kelompok-2_frontend
    ports:
      - "5011:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
  
volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
